# Generated by Django 4.1.5 on 2023-01-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackhours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='delta_time',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
