# Generated by Django 4.1.5 on 2023-01-26 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trackhours', '0005_alter_workday_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaportWorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Weak', max_length=20)),
                ('total', models.CharField(blank=True, max_length=25, null=True)),
                ('day1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day1', to='trackhours.workday')),
                ('day2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day2', to='trackhours.workday')),
                ('day3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day3', to='trackhours.workday')),
                ('day4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day4', to='trackhours.workday')),
                ('day5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day5', to='trackhours.workday')),
                ('day6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day6', to='trackhours.workday')),
                ('day7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day7', to='trackhours.workday')),
            ],
        ),
    ]
