# Generated by Django 4.1.5 on 2023-01-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackhours', '0006_raportworkday'),
    ]

    operations = [
        migrations.AddField(
            model_name='raportworkday',
            name='email',
            field=models.CharField(default='ruxhino@gmail.com', max_length=250),
        ),
    ]
