# Generated by Django 4.1.5 on 2023-01-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackhours', '0007_raportworkday_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_day', models.DateField()),
                ('end_date', models.DateField()),
                ('email', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='RaportWorkDay',
        ),
    ]
